steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying DAGs to Composer bucket..."
        gsutil -m rsync -r -d dags/ gs://us-central1-nyc-taxi-pipeli-6259b6ee-bucket/dags/
        echo "DAG deployment complete."

options:
  logging: CLOUD_LOGGING_ONLY